### ISSUE TITLE
envconsul 0.6.0 changed file names & layout

### ISSUE THREAD

**Issue by gozer** [reppard/puppet-envconsul#1]
They are zip files now

**Comment by reppard** [comment]
Thanks for the heads up.  I'll work on fixing this as soon as I can.  If you have cycles please feel free to submit a PR!

**Comment by reppard** [comment]
This is fixed now.  The module now uses the hashicorp releases endpoint(which are all zips).  Params class was added so everything can be configured(such the releases_url).  Unzip is a requirement for zips obviously.  Tars are still usable given another source for release packages.  Thanks to @jniesen for https://github.com/reppard/puppet-envconsul/pull/5 !
